"""Alerts raised by the scorer

Revision ID: 2508e9ee3339
Revises: 
Create Date: 2026-09-02 09:32:35.578236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2508e9ee3339'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('tx_datetime', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('outcome', sa.SmallInteger(), nullable=True),
    sa.Column('scenario', sa.SmallInteger(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_alerts_id_desc', 'alerts', [sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_alerts_tx_datetime', 'alerts', ['tx_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_tx_datetime', table_name='alerts')
    op.drop_index('ix_alerts_id_desc', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
