"""Transactions a replay reads

Revision ID: 8cb7ef9f94f4
Revises: 2508e9ee3339
Create Date: 2026-09-02 15:01:16.854470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb7ef9f94f4'
down_revision: Union[str, Sequence[str], None] = '2508e9ee3339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('tx_datetime', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_fraud', sa.SmallInteger(), nullable=False),
    sa.Column('scenario', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_transactions_tx_datetime', 'transactions', ['tx_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_tx_datetime', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
